---
- name: create file
  hosts: all
  tasks:
    - name: Compress directory /path/to/foo/ into /path/to/foo.tgz
      community.general.archive:
        path: /path/to/foo
        dest: /path/to/foo.tgz
